def _get_all_ops(ir):
    """Scans the IR recursively and extracts every operation being used."""
    ops = set()
    def scan(instructions):
        for op, args, _ in instructions:
            ops.add(op)
            if op == "IF":
                ops.add(args[1][0])
            if op == "LOOP":
                scan(args[0])
    scan(ir.instructions)
    return ops

def generate_arduino(ir):
    ops = _get_all_ops(ir)
    
    # Analyze what hardware is actually needed
    uses_servo  = any(o.startswith("SERVO") for o in ops)
    uses_led    = any(o.startswith("LED") for o in ops)
    uses_buzzer = any(o.startswith("BUZZER") for o in ops)
    uses_motor  = any(o in ("MOVE_FORWARD", "MOVE_BACKWARD", "TURN_LEFT", "TURN_RIGHT", "STOP") for o in ops)
    uses_wait   = "WAIT" in ops or uses_led or uses_buzzer or uses_motor

    # Build the Header dynamically
    code = "// Auto-generated by AutoLang Compiler\n\n"
    
    if uses_servo:
        code += "#include <Servo.h>\nServo myServo;\n#define SERVO_PIN 9\n"
    if uses_led:
        code += "#define LED_PIN 13\n"
    if uses_buzzer:
        code += "#define BUZZER_PIN 8\n"
    if uses_motor:
        code += "#define LEFT_MOTOR 3\n#define RIGHT_MOTOR 5\n"

    # For sensor detection (used in IF statements)
    code += "#define TRIG_PIN 10\n"

    # Build the Setup function dynamically
    code += "\nvoid setup() {\n    Serial.begin(9600);\n    pinMode(TRIG_PIN, INPUT);\n"
    
    if uses_servo:
        code += "    myServo.attach(SERVO_PIN);\n"
    if uses_led:
        code += "    pinMode(LED_PIN, OUTPUT);\n"
    if uses_buzzer:
        code += "    pinMode(BUZZER_PIN, OUTPUT);\n"
    if uses_motor:
        code += "    pinMode(LEFT_MOTOR, OUTPUT);\n    pinMode(RIGHT_MOTOR, OUTPUT);\n"

    code += "\n    // AutoLang Execution starts here\n"

    # Inject the User's Logic
    for op, args, _ in ir.instructions:
        code += _emit(op, args) + "\n"

    code += "}\n\nvoid loop() {\n    // Empty unless REPEAT logic is used\n}\n\n"

    # Inject ONLY the required Hardware Abstraction Functions
    code += "// --- Hardware Abstraction Functions ---\n"
    
    if uses_wait:
        code += "void waitSeconds(int s) { delay(s * 1000); }\n"
        
    if uses_led:
        code += "void ledOn() { digitalWrite(LED_PIN, HIGH); }\n"
        code += "void ledOff() { digitalWrite(LED_PIN, LOW); }\n"
        code += "void ledBlink(int times) {\n"
        code += "  for(int i=0; i<times; i++) {\n"
        code += "    digitalWrite(LED_PIN, HIGH); delay(200);\n"
        code += "    digitalWrite(LED_PIN, LOW); delay(200);\n"
        code += "  }\n}\n"

    if uses_buzzer:
        code += "void buzzerOn() { digitalWrite(BUZZER_PIN, HIGH); }\n"
        code += "void buzzerOff() { digitalWrite(BUZZER_PIN, LOW); }\n"
        code += "void buzzerBeep(int times) {\n"
        code += "  for(int i=0; i<times; i++) {\n"
        code += "    digitalWrite(BUZZER_PIN, HIGH); delay(100);\n"
        code += "    digitalWrite(BUZZER_PIN, LOW); delay(100);\n"
        code += "  }\n}\n"

    if uses_motor:
        code += "void moveForward(int d) { digitalWrite(LEFT_MOTOR, HIGH); digitalWrite(RIGHT_MOTOR, HIGH); delay(d*100); stopRobot(); }\n"
        code += "void moveBackward(int d) { digitalWrite(LEFT_MOTOR, LOW); digitalWrite(RIGHT_MOTOR, LOW); delay(d*100); stopRobot(); }\n"
        code += "void turnLeft(int a) { digitalWrite(RIGHT_MOTOR, HIGH); digitalWrite(LEFT_MOTOR, LOW); delay(a*10); stopRobot(); }\n"
        code += "void turnRight(int a) { digitalWrite(LEFT_MOTOR, HIGH); digitalWrite(RIGHT_MOTOR, LOW); delay(a*10); stopRobot(); }\n"
        code += "void stopRobot() { digitalWrite(LEFT_MOTOR, LOW); digitalWrite(RIGHT_MOTOR, LOW); }\n"

    return code


def _emit(op, args):
    if op == "LED_ON":        return "    ledOn();"
    if op == "LED_OFF":       return "    ledOff();"
    if op == "LED_BLINK":     return f"    ledBlink({args[0]});"
    if op == "BUZZER_ON":     return "    buzzerOn();"
    if op == "BUZZER_OFF":    return "    buzzerOff();"
    if op == "BUZZER_BEEP":   return f"    buzzerBeep({args[0]});"
    if op == "SERVO_MOVE":    return f"    myServo.write({args[0]});"
    if op == "MOVE_FORWARD":  return f"    moveForward({args[0]});"
    if op == "MOVE_BACKWARD": return f"    moveBackward({args[0]});"
    if op == "TURN_LEFT":     return f"    turnLeft({args[0]});"
    if op == "TURN_RIGHT":    return f"    turnRight({args[0]});"
    if op == "WAIT":          return f"    waitSeconds({args[0]});"
    if op == "STOP":          return "    stopRobot();"
    if op == "LOOP":
        inner = "\n".join(_emit(iop, iargs) for iop, iargs, _ in args[0])
        return f"    while (true) {{\n{inner}\n    }}"
    if op == "BREAK":
        return "    break;"
    if op == "IF":
        inner = _emit(args[1][0], args[1][1])
        # Very basic IF compilation for sensor detection
        return f"    if (digitalRead(TRIG_PIN) == HIGH) {{\n    {inner}\n    }}"
    return f"    // unhandled {op}"