# compiler/generator.py

HEADER = r"""// Auto-generated by AutoLang Compiler
// Standalone C++ program (no Arduino required)

#include <iostream>
#include <thread>
#include <chrono>
#include <cstdlib>

// ---------- Robot runtime (simulated) ----------
static int  robot_x = 0;
static int  robot_y = 0;
static int  robot_angle = 0;      // degrees, 0 = facing +X
static bool led_state = false;

static void sleep_ms(int ms) {
    std::this_thread::sleep_for(std::chrono::milliseconds(ms));
}

void moveForward(int d) {
    std::cout << "[MOVE]  forward  " << d << " units\n";
    robot_x += d;
    sleep_ms(200);
}
void moveBackward(int d) {
    std::cout << "[MOVE]  backward " << d << " units\n";
    robot_x -= d;
    sleep_ms(200);
}
void turnLeft(int a) {
    std::cout << "[TURN]  left  " << a << " degrees\n";
    robot_angle = (robot_angle - a) % 360;
    sleep_ms(150);
}
void turnRight(int a) {
    std::cout << "[TURN]  right " << a << " degrees\n";
    robot_angle = (robot_angle + a) % 360;
    sleep_ms(150);
}
void ledOn()  { led_state = true;  std::cout << "[LED]   ON\n"; }
void ledOff() { led_state = false; std::cout << "[LED]   OFF\n"; }
void ledBlink(int n) {
    for (int i = 0; i < n; ++i) {
        ledOn();  sleep_ms(200);
        ledOff(); sleep_ms(200);
    }
}
void waitSeconds(int s) {
    std::cout << "[WAIT]  " << s << " s\n";
    sleep_ms(s * 1000);
}
void stopRobot() {
    std::cout << "[STOP]  robot halted\n";
}

// Simulated sensors (replace with real sensor reads on hardware)
bool obstacleDetected() { return false; }
bool sensorDetect()     { return false; }

// ---------- Program ----------
int main() {
    std::cout << "=== AutoLang program start ===\n";
"""

FOOTER = r"""    std::cout << "=== AutoLang program end ===\n";
    std::cout << "Final position: (" << robot_x << "," << robot_y
              << ") angle=" << robot_angle << "\n";
    return 0;
}
"""

def _emit(op, args):
    if op == "MOVE_FORWARD":  return f"    moveForward({args[0]});"
    if op == "MOVE_BACKWARD": return f"    moveBackward({args[0]});"
    if op == "TURN_LEFT":     return f"    turnLeft({args[0]});"
    if op == "TURN_RIGHT":    return f"    turnRight({args[0]});"
    if op == "LED_ON":        return "    ledOn();"
    if op == "LED_OFF":       return "    ledOff();"
    if op == "LED_BLINK":     return f"    ledBlink({args[0]});"
    if op == "WAIT":          return f"    waitSeconds({args[0]});"
    if op == "STOP":          return "    stopRobot();"
    if op == "IF":
        cond, inner = args
        c = "obstacleDetected()" if "OBSTACLE" in cond else "sensorDetect()"
        return f"    if ({c}) {{\n    {_emit(inner[0], inner[1])}\n    }}"
    return f"    // unhandled {op}"

def generate(ir):
    body = "\n".join(_emit(op, args) for op, args, _ in ir.instructions)
    return HEADER + body + "\n" + FOOTER